name: Validate and build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-validate:
    name: Build and validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'

      - name: Install
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Run 2022
        run: yarn 2022

      - name: Run 2023
        run: yarn 2023
